__package__ = 'asprin'
__description__ = 'Qualitative and quantitative optimization in answer set programming'
__author__ = 'Javier Romero'
__email__ = 'javier@cs.uni-potsdam.de'
__license__ = 'MIT'
__version__ = '3.0.0'
__url__ = 'https://github.com/potassco/asprin'
